import 'package:flutter/material.dart';
import 'package:flutterapp/paprikaapp/generatedframe118widget/generated/GeneratedFrame34Widget.dart';
import 'package:flutterapp/paprikaapp/generatedframe118widget/generated/GeneratedGroup115Widget.dart';
import 'package:flutterapp/paprikaapp/generatedframe118widget/generated/GeneratedComponent3Widget.dart';
import 'package:flutterapp/paprikaapp/generatedframe118widget/generated/GeneratedWidget4.dart';
import 'package:flutterapp/paprikaapp/generatedframe118widget/generated/GeneratedWidget1.dart';

/* Frame Frame 118
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame118Widget extends StatelessWidget {
  const GeneratedFrame118Widget({Key key,  this.countShop,}) : super(key: key);
  final int countShop;
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 376.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.only(
          topLeft: Radius.circular(24.0),
          topRight: Radius.circular(24.0),
          bottomRight: Radius.circular(0.0),
          bottomLeft: Radius.circular(0.0),
        ),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.only(
                topLeft: Radius.circular(24.0),
                topRight: Radius.circular(24.0),
                bottomRight: Radius.circular(0.0),
                bottomLeft: Radius.circular(0.0),
              ),
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 16.0,
              top: 16.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 24.0,
              child: GeneratedFrame34Widget(),
            ),
            Positioned(
              left: 16.0,
              top: 56.0,
              right: null,
              bottom: null,
              width: 345.0,
              height: 26.0,
              child: GeneratedWidget1(),
            ),
            Positioned(
              left: 16.0,
              top: 96.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 154.0,
              child: GeneratedGroup115Widget(countShop: countShop),
            ),
            Positioned(
              left: 16.0,
              top: 266.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 58.0,
              child: GeneratedComponent3Widget(countShop: countShop,),
            ),
            Positioned(
              left: 16.0,
              top: 340.0,
              right: null,
              bottom: null,
              width: 345.0,
              height: 18.0,
              child: GeneratedWidget4(),
            )
          ]),
    ));
  }
}
